### ISSUE TITLE
Properties on Constructor

### ISSUE THREAD

**Issue by davidbarro** [opentok/web-components#13]
Hello,

My application is developed in ReactJs and I wanted to migrate from the opentok-react package to this new one, but I get blocked, due to things that I don't see in this one.

If you could add the initialization properties of both VideoPublisher and VideoSubscriber to the constructor, it would be of great help.

For example, for the VideoPublisher component, it is possible to control the initialization of the publishAudio and publishVideo properties from the parent component.

`
<OTPublisher
  session={opentok}
  properties={{
    audioFallbackEnabled: false,
    showControls: false,
    publishAudio: controls.isAudioEnabled,
    publishVideo: controls.isVideoEnabled,
  }}
/>
`

I await your news
All the best.

**Comment by conshus** [comment]
Hey @davidbarro 
Thanks. We will be adding this in the next set of updates coming by next week.
Looking forward to hearing your feedback.

Thanks again.

**Comment by conshus** [comment]
Hey @davidbarro 

Just published updates to < video-publisher >, < video-subscribers >, < video-subscriber > and < screen-share > that allow you to pass in `properties`.

Let me know if this works out for you.

Thanks.

**Comment by davidbarro** [comment]
Hi @conshus

It still doesn't work correctly for me, for example when I change the fitMode to "contain", nothing happens, it stays in "cover" mode by default.

As another topic, how should the events of each of the components be listened to, for example the streamCreated of a publisher?
It would be necessary to be able to listen to the events in the following way:
`
eventHandlers={{
	streamCreated: () => // my function
}}
`

I'm waiting

Greetings.

**Comment by conshus** [comment]
Hey @davidbarro 

Can you provide the code where you are setting the fitMode property?

Events like `streamCreated` happen at the session level so you'd want to listen for them in your application. The components wouldn't emit session level events, just errors that happen with the component.

There's an example with the <video-subscriber> component (https://github.com/opentok/web-components/tree/main/video-subscriber#getting-it-to-work) where you listen for a `streamCreated` session event to know when to add another subscriber.

Let me know if this helps.
