### ISSUE TITLE
Video Publisher properties not working + examples need update (react)

### ISSUE THREAD

**Issue by georgesofianosgr** [opentok/web-components#21]
I was trying to use the react example with web-components.
Unfortunately the code has changed(v 0.0.5) and width/height attributes no longer work, as a result video element was not visible.

I checked the code in the current version and then I added the properties attribute but still no video element was visible.
```jsx
 <video-publisher properties={{width: '240px', height: '160px', insertMode: 'append'}} ref={publisher} />
```

I added some logs in the video-publisher library and I found out that **this.properties** was null.
Later I successfully applied the properties via the publisher reference
```jsx
publisher.current.properties = {width: '240px', height: '160px', insertMode: 'append'}
``` 

Please update the examples because it took me a lot of time researching the problem.
Also I am not sure If properties attribute has a bug or I am doing something wrong.

**Comment by conshus** [comment]
Hi @georgesofianosgr. 
> Unfortunately the code has changed(v 0.0.5) and width/height attributes no longer work, as a result video element was not visible.

Thanks for the catch, I'll remove width and height from the docs and code. Yeah, folks wanted to be able to modify more properties than I originally intended.

As for properties:
You can't pass in objects into an element's attributes, just strings. I think when React gets full compatibility with Web Component standards, you should be able to pass in objects, just like other frameworks can. https://custom-elements-everywhere.com/ 

So if you stringified your object, and placed it in the tag, it should work, but it's probably easier to set it on the reference as you did and how it states in the docs for setting the session (an object) and token.

```
publisher.current.session = session;
publisher.current.token = token;
subscribers.current.session = session;
subscribers.current.token = token;
screenshare.current.session = session;
screenshare.current.token = token;
```

I'll make it more explicit in the docs on how to set the properties.
