### ISSUE TITLE
Publisher is generating videos in 4:3 when the resolution is set to 1920x1080

### ISSUE THREAD

**Issue by fi5u** [opentok/web-components#22]
I cannot figure out how to get the camera to record in 16:9 format. I'm switching over from using the React Native implementation where I was able to record video in 16:9. Using these web components, I have the following settings, but still I have black bars on the side of my recorded video.

```
<video-publisher
  properties={{
    fitMode: "cover",
    height: 1080,
    resolution: "1920x1080",
    videoContentHint: "detail",
    width: 1920,
  }}
  ref={publisher}
  style={{ display: "block", minWidth: 360, minHeight: 240 }}
></video-publisher>
```

<img width="673" alt="Screenshot 2023-09-01 at 12 46 14" src="https://github.com/opentok/web-components/assets/1974868/19d666a9-2e31-4473-aabf-cf3c44cd2fdd">

I'd be grateful for any advice here.

**Comment by conshus** [comment]
Hi @fi5u

Thanks for the post. I'll look into this, but I suspect it could be the way you are setting the properties. Looks like you are setting them as if <video-publisher> was a React Component.

I think if you set the properties in the same place you set your token and session, it should work properly.
for example:
```
   const publisher = useRef(null);
    publisher.current.properties = {
      fitMode: 'cover',
      height: '1080px',
      resolution: '1920x1080',
      videoContentHint: 'detail',
      width: '1920px',
    };
```
Let me know if this worked for you.
Thanks.

**Comment by fi5u** [comment]
Hi @conshus, thanks for getting back to me. Yes, that seems to fix it. Many thanks!

**Comment by conshus** [comment]
Awesome @fi5u! Thanks for trying out the Web Components and leaving feedback. Feel free to do so more in the future.
