### ISSUE TITLE
Cannot connect, the session is already connecting

### ISSUE THREAD

**Issue by webpipl** [opentok/web-components#28]
common.js:118 OpenTok:Session:warn OT.Session: Cannot connect, the session is already connecting, because library already connecting from 2 methods to sessioon publisher,subscriber,subscribers components , even though we are not checking it weather its already session connected or not 
**VideoPublisher.js**
![image](https://github.com/opentok/web-components/assets/51621445/f52eb88a-eb1d-4ef1-bd6e-4a268c2f3df9)

**Screen Share**
![image](https://github.com/opentok/web-components/assets/51621445/fc2a1d56-e118-4bda-ac95-1e1eeca3147b)
 Can you please let us knew , why should we try to connect multiple times

And can i implement multiple participants view speaker view?

I think need more clear documentation about web components?

**Comment by conshus** [comment]
Hi. Not sure if I understand. Did something break?
> Can you please let us knew , why should we try to connect multiple times

The Web Components can be used independently of each other and each is connecting to the session. So for example, you can have a page with just all the subscribers for people just viewing the call and not participating. If you only had one component on the page, you shouldn't get the warning.

> And can i implement multiple participants view speaker view?

Still not sure what you mean, by "multiple participants view speaker view". If you mean you want to see all the subscribers to the call, you can use < video-subscribers >. The demos have a section with the publisher and another where all the other participants are displayed. Could you provide an example of what you are looking to do?

> I think need more clear documentation about web components?

The Video API Web Components are a set of self-contained UI elements for video chat. They allow a developer to just place the element inside of their application and not have to worry about things like initializing and setting up event listeners. Hope that helps clear things up.
